/*
 *  
 *  Copyright (C) 2010, 2011, 2012 The Europa Barbarorum Team
 *  All rights reserved.
 *  
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *      * Redistributions of source code must retain the above copyright
 *        notice, this list of conditions and the following disclaimer.
 *      * Redistributions in binary form must reproduce the above copyright
 *        notice, this list of conditions and the following disclaimer in the
 *        documentation and/or other materials provided with the distribution.
 *      * Neither the name of The Europa Barbarorum Team nor the
 *        names of other contributors may be used to endorse or promote products
 *        derived from this software without specific prior written permission.
 *  
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED. IN NO EVENT SHALL The Europa Barbarorum Team BE LIABLE FOR ANY
 *  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *  
 */

/*
 * CUFFileUI.java
 *
 * Created on Oct 2, 2010, 4:22:05 PM
 */
package org.europabarbarorum.cuf.gui.fontwizard.common;

import java.util.ResourceBundle;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import org.europabarbarorum.cuf.gui.fontwizard.common.CUFFileUI.Model;
import org.europabarbarorum.cuf.gui.support.ComponentState;
import org.europabarbarorum.cuf.gui.support.ComponentState.ComponentModel;
import org.europabarbarorum.cuf.gui.support.FileInput;
import org.europabarbarorum.cuf.gui.support.FileType;
import org.europabarbarorum.cuf.gui.support.SettingField;
import org.europabarbarorum.cuf.shell.Shell;

/**
 * A form element to enter the path to a CUF file.
 * @author Johan Ouwerkerk
 */
public class CUFFileUI extends JPanel implements
        ComponentState<Model> {

    private final FileInput file;


    /**
     * Create a new {@link CUFFileUI} for GUI builder purposes.
     * Makes this class a valid JavaBean.
     */
    public CUFFileUI () {
        this(null);
    }

   /**
    * Create a new {@link CUFFileUI}.
    * @param shell the context {@link Shell} to use for resolving relative path names.
    */
    public CUFFileUI (Shell shell) {
        file = new FileInput(FileType.CUF.derive(false, true),
                             FileInput.Access.Read,
                             shell,
                             this);
        initComponents();
    }

    @Override
    public Model createModel () {
        return new Model(file.getValue());
    }

    @Override
    public boolean checkUI () {
        return file.check();
    }

    /**
     * A {@link ComponentModel} for a {@link CUFFileUI}.
     */
    public static class Model implements ComponentModel<CUFFileUI> {

        private Model (String s) {
            this.path=s;
        }
        /**
         * The path name entered in the {@link CUFFileUI} represented by this {@link Model}.
         */
        public final String path;

        @Override
        public void populate (CUFFileUI ui) {
            ui.file.getTextField().setValue(path);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JButton load = file.getButton();
        SettingField field = file.getTextField();
        JLabel label = new JLabel();

        setName("Form"); // NOI18N

        ResourceBundle bundle = ResourceBundle.getBundle("org/europabarbarorum/cuf/gui/fontwizard/common/CommonUI"); // NOI18N
        load.setText(bundle.getString("CUFFileUI.load.text")); // NOI18N
        load.setName("load"); // NOI18N

        field.setText(bundle.getString("CUFFileUI.field.text")); // NOI18N
        field.setName("field"); // NOI18N

        label.setText(bundle.getString("CUFFileUI.label.text")); // NOI18N
        label.setName("label"); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(field, GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(load)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(load)
                    .addComponent(field, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
